name: BSMRU Admin Panel
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-letest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

      - name: Install NPM Dependencies
        run: npm install

      - name: Build NPM Dependencies
        run: npm run build

      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'



      # - name: Synchronize Files To Server
      #   uses: easingthemes/ssh-deploy@v2.1.5
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SOURCE: "."
      #     REMOTE_HOST: ${{ secrets.VPS_HOST }}
      #     REMOTE_USER: ${{ secrets.VPS_USER }}
      #     TARGET: "/var/www/html/glennraya.com"

      # - name: Run Remote/Artisan Commands
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.VPS_HOST }}
      #     username: ${{ secrets.VPS_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /var/www/html/glennraya.com
      #       php artisan migrate --force
      #       php artisan optimize

